//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yura.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yura.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is currently not supported for deep search..
        /// </summary>
        internal static string DeepSearchNotSupported {
            get {
                return ResourceManager.GetString("DeepSearchNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export files.
        /// </summary>
        internal static string FailedExportFiles {
            get {
                return ResourceManager.GetString("FailedExportFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open bigfile.
        /// </summary>
        internal static string FailedOpenBigfile {
            get {
                return ResourceManager.GetString("FailedOpenBigfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write file.
        /// </summary>
        internal static string FailedWriteFile {
            get {
                return ResourceManager.GetString("FailedWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File part not found.
        /// </summary>
        internal static string FilePartNotFound {
            get {
                return ResourceManager.GetString("FilePartNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A part of the bigfile was not found, make sure you are using the right alignment and your game files are complete..
        /// </summary>
        internal static string FilePartNotFoundMessage {
            get {
                return ResourceManager.GetString("FilePartNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game not supported.
        /// </summary>
        internal static string GameNotSupported {
            get {
                return ResourceManager.GetString("GameNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bigfile open.
        /// </summary>
        internal static string NoBigfileOpen {
            get {
                return ResourceManager.GetString("NoBigfileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bigfile is open, open a bigfile under &apos;File &gt; Open&apos;..
        /// </summary>
        internal static string NoBigfileOpenMessage {
            get {
                return ResourceManager.GetString("NoBigfileOpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bigfile is open, open a bigfile under &apos;File &gt; Open&apos; and reopen this window..
        /// </summary>
        internal static string NoBigfileOpenMessage2 {
            get {
                return ResourceManager.GetString("NoBigfileOpenMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game selected.
        /// </summary>
        internal static string NoGameSelected {
            get {
                return ResourceManager.GetString("NoGameSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not select a game, make sure to select one using the &apos;Game&apos; dropdown..
        /// </summary>
        internal static string NoGameSelectedMessage {
            get {
                return ResourceManager.GetString("NoGameSelectedMessage", resourceCulture);
            }
        }
    }
}
